import HowiWork from 'components/About/HowiWork'
import InfiniteScroll1 from 'components/About/InfiniteScroll'
import Intro from 'components/About/Intro'
import Quote from 'components/About/Quote'
import Story from 'components/About/Story'
import WhatiUse from 'components/About/WhatiUse'
import Footer from 'components/Home/Footer'
import Navbar from 'components/Home/Navbar'
import Layout from 'components/Layout/Layout'
import Head from 'next/head'


const About = () => {
  return (
    
      <Layout>
         <Head>
        <title>Jabir Khan - About me</title>
        <meta name="description" content="Generated by Jabir Khan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar/>
        <Intro/>
        <Story/>
        <InfiniteScroll1/>
        <HowiWork/>
        <WhatiUse/>
        <Quote/>
        <Footer/>
        </Layout>
  )
}

export default About