import HeroSection from "components/Contact/HeroSection"
import Footer from "components/Home/Footer"
import Navbar from "components/Home/Navbar"
import Layout from "components/Layout/Layout"
import Head from "next/head"

const Contact = () => {
  return (
    <Layout>
       <Head>
        <title>Jabir Khan - Contact</title>
        <meta name="description" content="Generated by Jabir Khan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar/>
    <div style={{backgroundColor:'white'}}>
        <HeroSection/>
        <Footer/>
    </div>
    </Layout>
  )
}

export default Contact