import CraftedWithLove from "components/Home/CraftedWithLove"
import Footer from "components/Home/Footer"
import HeroSection from "components/Home/HeroSection"
import HomePageProjects from "components/Home/HomePageProjects"
import Navbar from "components/Home/Navbar"

import TheresMore from "components/Home/TheresMore"
import Layout from "components/Layout/Layout"
import Head from "next/head";


const HomePage = () => {
  return (
      <Layout>
         <Head>
        <title>Jabir Khan - Home</title>
        <meta name="description" content="Generated by Jabir Khan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar/>
        <HeroSection/>
        <CraftedWithLove/>
        <HomePageProjects/>
        <TheresMore/>
        <Footer/>
        </Layout>
  )
}

export default HomePage