import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";
import LoadingBar from "react-top-loading-bar";
import { useRouter } from "next/router";
import { motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [progValue, setProgValue] = useState(0);
  const [isProgComplete, setIsProgComplete] = useState(false);
  const router = useRouter();

  if (isProgComplete) {
    router.replace("/home");
  }

  useEffect(() => {
    const intervalClear = setInterval(() => {
      setProgValue((prevValue) => prevValue + (250 / 3000) * 100);
    }, 250);
    setTimeout(() => {
      clearInterval(intervalClear);
      setIsProgComplete(true);
    }, 3000);
  }, []);

  return (
    <>
      <Head>
        <title>Jabir Khan</title>
        <meta name="description" content="Generated by Jabir Khan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        style={{
          width: "100%",
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          position: "relative",
        }}
      >
        <motion.h1
          initial={{ opacity: 0, }}
          animate={{ opacity:1,}}
          transition={{ease:'easeOut', duration:1}}
          style={{fontWeight:'normal'}}
        >
          Jabir Khan
        </motion.h1>
        <div style={{ width: "20rem", position: "relative" }}>
          <LoadingBar
            progress={progValue}
            loaderSpeed={800}
            color="#474747"
            style={{ marginTop: "1rem",height:'3px', background: "#474747" }}
            containerStyle={{ top: "10%", position: "absolute" }}
            onLoaderFinished={() => setIsProgComplete(true)}
          />
        </div>
      </div>
    </>
  );
}
