import Footer from 'components/Home/Footer'
import Navbar from 'components/Home/Navbar'
import Layout from 'components/Layout/Layout'
import GithubProjects from 'components/Works/GithubProjects'
import HeroSection from 'components/Works/HeroSection'
import ProjectsContainer from 'components/Works/ProjectsContainer'
import Head from 'next/head'


const Works = () => {
  return (
    <Layout>
       <Head>
        <title>Jabir Khan - Works</title>
        <meta name="description" content="Generated by Jabir Khan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar/>
    <div style={{backgroundColor:'white'}}>
        <HeroSection/>
        <ProjectsContainer/>
        <GithubProjects/>
        <Footer/>
    </div>
    </Layout>
  )
}

export default Works